spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
 
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: green
    password: green1234
    url: jdbc:mariadb://localhost:3306/greendb?serverTimezone=Asia/Seoul
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
